name: ci

on:
  push:
    branches:
    - main
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: |
          chmod +x tools/tweego/tweego
          tools/tweego/tweego  src/ -o out/story.html
          
      - uses: actions/upload-artifact@v3
        with:
          name: story.html
          path: out/story.html
